[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
fund-contract = "H9txrMrTfGU6LXYWBzMHzmzuQWbNYcW1vHFLRcxCYiKn"
token-program = "33pHXYQbe41JJSA7oXor6h7JFY74eqH25xtSjBysmTYo"
base-token-program = "7iaDbVGbVJdhZcKXWQmMw783nBqfDyx6K8V4yF6Kv8iq"
interop-core = "5dyQmihDcQqCBerQg82J19QxMByjpxbwdtmCuPkT9ePD"
interop-multisig = "2uuBHq3teujBvfE3AnRm4LZFYk7sHUiC36Z9MdkgcJ2N"
treasury-bond = "53cKZWTPTwLjXD7E6NHCQzn5Gs9KL81u5xqicHEJwNgE"
z-rwa = "3SN3zAmuW5HWgJy5mcWjvy8vwDZRLosEajqydbuxiEZC"
compliance_vault = "CPvaLtbD6WeA5j1Q5sR7T5rJ6n1VbM5Fj8yQd1d11Zq"

[programs.devnet]
fund-contract = "H9txrMrTfGU6LXYWBzMHzmzuQWbNYcW1vHFLRcxCYiKn"
token-program = "33pHXYQbe41JJSA7oXor6h7JFY74eqH25xtSjBysmTYo"
base-token-program = "7iaDbVGbVJdhZcKXWQmMw783nBqfDyx6K8V4yF6Kv8iq"
interop-core = "5dyQmihDcQqCBerQg82J19QxMByjpxbwdtmCuPkT9ePD"
interop-multisig = "2uuBHq3teujBvfE3AnRm4LZFYk7sHUiC36Z9MdkgcJ2N"
treasury-bond = "53cKZWTPTwLjXD7E6NHCQzn5Gs9KL81u5xqicHEJwNgE"
z-rwa = "3SN3zAmuW5HWgJy5mcWjvy8vwDZRLosEajqydbuxiEZC"
compliance_vault = "CPvaLtbD6WeA5j1Q5sR7T5rJ6n1VbM5Fj8yQd1d11Zq"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"



[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test-2.ts"
