provenanced tx trigger create-tx-trigger event.json msg.json \
    --from $dev \
    --custom-denom OasisToken \
    --keyring-backend test \
    --home $prov_path \
    --chain-id pio-axl-devnet-1 \
    --gas auto \
    --gas-prices 0OasisToken \
    --broadcast-mode block \
    --yes \
    --testnet \
	--output json \
    --generate-only \
	--node=http://34.70.126.95:26657 |  jq
